name: Format code

on: [pull_request]

jobs:
  cleanup_tasks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Prettier
        uses: creyD/prettier_action@master
        with:
          prettier_options: --write **/*.js --single-quote
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
